### ISSUE TITLE
What this gem actually does under the hood?

### ISSUE THREAD

**Issue by salmanasiddiqui** [betterup/devise-doorkeeper#11]
Hi @wireframe ,
I have looked into this gem code. But I lack knowledge of [doorkeeper gem](https://github.com/doorkeeper-gem/doorkeeper) (actually I came to know about it few hours ago).

I have used [devise_token_auth](https://github.com/lynndylanhurley/devise_token_auth) and [ng-token-auth](https://github.com/lynndylanhurley/ng-token-auth). But its not Oauth compliant. I was wondering doesn't this gem `devise-doorkeeper`  should actually be using `devise_token_auth` and `doorkeeper`? What is the actual application of this gem?

Thanks

**Comment by wireframe** [comment]
per the readme:
> The devise-doorkeeper gem allows your existing Devise application to accept OAuth2 tokens created by the Doorkeeper authorization flow.

device_token_auth is not an Oauth provider.  this gem is a drop in solution for rails apps using devise to include oauth functionality.
